/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vramachandran' at '4/23/16 12:51 PM' with Gradle 2.2.1
 *
 * @author vramachandran, @date 4/23/16 12:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
